var wms_layers = [];
var baseLayer = new ol.layer.Group({
    'title': '',
    layers: [
new ol.layer.Tile({
    'title': 'OSM',
    'type': 'base',
    source: new ol.source.OSM()
})
]
});
var format_ZipCodes_0 = new ol.format.GeoJSON();
var features_ZipCodes_0 = format_ZipCodes_0.readFeatures(json_ZipCodes_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ZipCodes_0 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_ZipCodes_0.addFeatures(features_ZipCodes_0);var lyr_ZipCodes_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_ZipCodes_0, 
                style: style_ZipCodes_0,
                title: '<img src="styles/legend/ZipCodes_0.png" /> Zip Codes'
            });var format_Roadsegments_1 = new ol.format.GeoJSON();
var features_Roadsegments_1 = format_Roadsegments_1.readFeatures(json_Roadsegments_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Roadsegments_1 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_Roadsegments_1.addFeatures(features_Roadsegments_1);var lyr_Roadsegments_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Roadsegments_1, 
                style: style_Roadsegments_1,
                title: '<img src="styles/legend/Roadsegments_1.png" /> Road segments'
            });var format_CongestionAllZip_2 = new ol.format.GeoJSON();
var features_CongestionAllZip_2 = format_CongestionAllZip_2.readFeatures(json_CongestionAllZip_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionAllZip_2 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionAllZip_2.addFeatures(features_CongestionAllZip_2);var lyr_CongestionAllZip_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionAllZip_2, 
                style: style_CongestionAllZip_2,
                title: '<img src="styles/legend/CongestionAllZip_2.png" /> Congestion All (Zip)'
            });var format_CongestionComparisonStreetAll_3 = new ol.format.GeoJSON();
var features_CongestionComparisonStreetAll_3 = format_CongestionComparisonStreetAll_3.readFeatures(json_CongestionComparisonStreetAll_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionComparisonStreetAll_3 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionComparisonStreetAll_3.addFeatures(features_CongestionComparisonStreetAll_3);var lyr_CongestionComparisonStreetAll_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionComparisonStreetAll_3, 
                style: style_CongestionComparisonStreetAll_3,
                title: '<img src="styles/legend/CongestionComparisonStreetAll_3.png" /> Congestion Comparison (Street) All'
            });var format_CongestionNightZip_4 = new ol.format.GeoJSON();
var features_CongestionNightZip_4 = format_CongestionNightZip_4.readFeatures(json_CongestionNightZip_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionNightZip_4 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionNightZip_4.addFeatures(features_CongestionNightZip_4);var lyr_CongestionNightZip_4 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionNightZip_4, 
                style: style_CongestionNightZip_4,
                title: '<img src="styles/legend/CongestionNightZip_4.png" /> Congestion Night (Zip)'
            });var format_CongestionComparisonStreetNT_5 = new ol.format.GeoJSON();
var features_CongestionComparisonStreetNT_5 = format_CongestionComparisonStreetNT_5.readFeatures(json_CongestionComparisonStreetNT_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionComparisonStreetNT_5 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionComparisonStreetNT_5.addFeatures(features_CongestionComparisonStreetNT_5);var lyr_CongestionComparisonStreetNT_5 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionComparisonStreetNT_5, 
                style: style_CongestionComparisonStreetNT_5,
                title: '<img src="styles/legend/CongestionComparisonStreetNT_5.png" /> Congestion Comparison (Street) NT'
            });var format_CongestionAfternoonZip_6 = new ol.format.GeoJSON();
var features_CongestionAfternoonZip_6 = format_CongestionAfternoonZip_6.readFeatures(json_CongestionAfternoonZip_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionAfternoonZip_6 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionAfternoonZip_6.addFeatures(features_CongestionAfternoonZip_6);var lyr_CongestionAfternoonZip_6 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionAfternoonZip_6, 
                style: style_CongestionAfternoonZip_6,
                title: '<img src="styles/legend/CongestionAfternoonZip_6.png" /> Congestion Afternoon (Zip)'
            });var format_CongestionComparisonStreetPM_7 = new ol.format.GeoJSON();
var features_CongestionComparisonStreetPM_7 = format_CongestionComparisonStreetPM_7.readFeatures(json_CongestionComparisonStreetPM_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionComparisonStreetPM_7 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionComparisonStreetPM_7.addFeatures(features_CongestionComparisonStreetPM_7);var lyr_CongestionComparisonStreetPM_7 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionComparisonStreetPM_7, 
                style: style_CongestionComparisonStreetPM_7,
                title: '<img src="styles/legend/CongestionComparisonStreetPM_7.png" /> Congestion Comparison (Street) PM'
            });var format_CongestionNoonZip_8 = new ol.format.GeoJSON();
var features_CongestionNoonZip_8 = format_CongestionNoonZip_8.readFeatures(json_CongestionNoonZip_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionNoonZip_8 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionNoonZip_8.addFeatures(features_CongestionNoonZip_8);var lyr_CongestionNoonZip_8 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionNoonZip_8, 
                style: style_CongestionNoonZip_8,
                title: '<img src="styles/legend/CongestionNoonZip_8.png" /> Congestion Noon (Zip)'
            });var format_CongestionComparisonStreetMD_9 = new ol.format.GeoJSON();
var features_CongestionComparisonStreetMD_9 = format_CongestionComparisonStreetMD_9.readFeatures(json_CongestionComparisonStreetMD_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionComparisonStreetMD_9 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionComparisonStreetMD_9.addFeatures(features_CongestionComparisonStreetMD_9);var lyr_CongestionComparisonStreetMD_9 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionComparisonStreetMD_9, 
                style: style_CongestionComparisonStreetMD_9,
                title: '<img src="styles/legend/CongestionComparisonStreetMD_9.png" /> Congestion Comparison (Street) MD'
            });var format_CongestionMorningZip_10 = new ol.format.GeoJSON();
var features_CongestionMorningZip_10 = format_CongestionMorningZip_10.readFeatures(json_CongestionMorningZip_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionMorningZip_10 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionMorningZip_10.addFeatures(features_CongestionMorningZip_10);var lyr_CongestionMorningZip_10 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionMorningZip_10, 
                style: style_CongestionMorningZip_10,
                title: '<img src="styles/legend/CongestionMorningZip_10.png" /> Congestion Morning (Zip)'
            });var format_CongestionComparisonStreetAM_11 = new ol.format.GeoJSON();
var features_CongestionComparisonStreetAM_11 = format_CongestionComparisonStreetAM_11.readFeatures(json_CongestionComparisonStreetAM_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CongestionComparisonStreetAM_11 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_CongestionComparisonStreetAM_11.addFeatures(features_CongestionComparisonStreetAM_11);var lyr_CongestionComparisonStreetAM_11 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_CongestionComparisonStreetAM_11, 
                style: style_CongestionComparisonStreetAM_11,
                title: '<img src="styles/legend/CongestionComparisonStreetAM_11.png" /> Congestion Comparison (Street) AM'
            });

lyr_ZipCodes_0.setVisible(true);lyr_Roadsegments_1.setVisible(false);lyr_CongestionAllZip_2.setVisible(false);lyr_CongestionComparisonStreetAll_3.setVisible(false);lyr_CongestionNightZip_4.setVisible(false);lyr_CongestionComparisonStreetNT_5.setVisible(false);lyr_CongestionAfternoonZip_6.setVisible(false);lyr_CongestionComparisonStreetPM_7.setVisible(false);lyr_CongestionNoonZip_8.setVisible(false);lyr_CongestionComparisonStreetMD_9.setVisible(false);lyr_CongestionMorningZip_10.setVisible(true);lyr_CongestionComparisonStreetAM_11.setVisible(false);
var layersList = [baseLayer,lyr_ZipCodes_0,lyr_Roadsegments_1,lyr_CongestionAllZip_2,lyr_CongestionComparisonStreetAll_3,lyr_CongestionNightZip_4,lyr_CongestionComparisonStreetNT_5,lyr_CongestionAfternoonZip_6,lyr_CongestionComparisonStreetPM_7,lyr_CongestionNoonZip_8,lyr_CongestionComparisonStreetMD_9,lyr_CongestionMorningZip_10,lyr_CongestionComparisonStreetAM_11];
lyr_ZipCodes_0.set('fieldAliases', {'POSTCODE': 'POSTCODE', 'PC_NAME': 'PC_NAME', 'PC_TYPE': 'PC_TYPE', 'PA_NAME': 'PA_NAME', 'PA_FIPS': 'PA_FIPS', 'City': 'City', 'County': 'County', 'AREA_SQMI': 'AREA_SQMI', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', });
lyr_Roadsegments_1.set('fieldAliases', {'OBJECTID_x': 'OBJECTID_x', 'TMC': 'TMC', 'ROAD_NUMBE': 'ROAD_NUMBE', 'Road': 'Road', 'DIRECTION_': 'DIRECTION_', 'SEGMENT_BE': 'SEGMENT_BE', 'SEGMENT_EN': 'SEGMENT_EN', 'County_x': 'County_x', 'ZIP_x': 'ZIP_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'ABS_DIRECT': 'ABS_DIRECT', 'Shape_Leng': 'Shape_Leng', 'travelT_20': 'travelT_20', 'OBJECTID_y': 'OBJECTID_y', 'ROAD_NUM_1': 'ROAD_NUM_1', 'ROAD_NAM_1': 'ROAD_NAM_1', 'DIRECTIO_1': 'DIRECTIO_1', 'SEGMENT__1': 'SEGMENT__1', 'SEGMENT__2': 'SEGMENT__2', 'County_y': 'County_y', 'ZIP_y': 'ZIP_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'ABS_DIRE_1': 'ABS_DIRE_1', 'Shape_Le_1': 'Shape_Le_1', 'travelT__1': 'travelT__1', 'travelT_in': 'travelT_in', });
lyr_CongestionAllZip_2.set('fieldAliases', {'Zip': 'Zip', 'PC_NAME': 'PC_NAME', 'PC_TYPE': 'PC_TYPE', 'PA_NAME': 'PA_NAME', 'PA_FIPS': 'PA_FIPS', 'City': 'City', 'County': 'County', 'AREA_SQMI': 'AREA_SQMI', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'ZIP': 'ZIP', 'ZIP_x': 'ZIP_x', 'OBJECTID_x': 'OBJECTID_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'congZip201': 'congZip201', 'congZip2_1': 'congZip2_1', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'congDiff': 'congDiff', 'congPercen': 'congPercen', 'tTZip2012': 'tTZip2012', 'tTZip2015': 'tTZip2015', 'travelTPer': 'travelTPer', 'speedZip20': 'speedZip20', 'speedZip_1': 'speedZip_1', 'speedPerce': 'speedPerce', 'Travel Tim': 'Travel Tim', 'Travel Tim_1': 'Travel Tim_1', 'Travel Tim_2': 'Travel Tim_2', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', 'S': 'S', 'Cong Diff': 'Cong Diff', });
lyr_CongestionComparisonStreetAll_3.set('fieldAliases', {'OBJECTID_x': 'OBJECTID_x', 'TMC': 'TMC', 'ROAD_NUMBE': 'ROAD_NUMBE', 'Road': 'Road', 'DIRECTION_': 'DIRECTION_', 'SEGMENT_BE': 'SEGMENT_BE', 'SEGMENT_EN': 'SEGMENT_EN', 'County_x': 'County_x', 'ZIP_x': 'ZIP_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'ABS_DIRECT': 'ABS_DIRECT', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'ROAD_NUM_1': 'ROAD_NUM_1', 'ROAD_NAM_1': 'ROAD_NAM_1', 'DIRECTIO_1': 'DIRECTIO_1', 'SEGMENT__1': 'SEGMENT__1', 'SEGMENT__2': 'SEGMENT__2', 'County_y': 'County_y', 'ZIP_y': 'ZIP_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'ABS_DIRE_1': 'ABS_DIRE_1', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'Travel Tim': 'Travel Tim', 'Travel Tim_1': 'Travel Tim_1', 'Travel Tim_2': 'Travel Tim_2', 'Cong Diff': 'Cong Diff', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', });
lyr_CongestionNightZip_4.set('fieldAliases', {'Zip': 'Zip', 'PC_NAME': 'PC_NAME', 'PC_TYPE': 'PC_TYPE', 'PA_NAME': 'PA_NAME', 'PA_FIPS': 'PA_FIPS', 'City': 'City', 'County': 'County', 'AREA_SQMI': 'AREA_SQMI', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'ZIP': 'ZIP', 'ZIP_x': 'ZIP_x', 'OBJECTID_x': 'OBJECTID_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'congZip201': 'congZip201', 'congZip2_1': 'congZip2_1', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'congDiff': 'congDiff', 'congPercen': 'congPercen', 'tTZip2012': 'tTZip2012', 'tTZip2015': 'tTZip2015', 'travelTPer': 'travelTPer', 'speedZip20': 'speedZip20', 'speedZip_1': 'speedZip_1', 'speedPerce': 'speedPerce', 'Travel Tim': 'Travel Tim', 'Travel Tim_1': 'Travel Tim_1', 'Travel Tim_2': 'Travel Tim_2', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', 'Speed Diff': 'Speed Diff', 'Cong Diff': 'Cong Diff', });
lyr_CongestionComparisonStreetNT_5.set('fieldAliases', {'OBJECTID_x': 'OBJECTID_x', 'TMC': 'TMC', 'ROAD_NUMBE': 'ROAD_NUMBE', 'Road ': 'Road ', 'DIRECTION_': 'DIRECTION_', 'SEGMENT_BE': 'SEGMENT_BE', 'SEGMENT_EN': 'SEGMENT_EN', 'County_x': 'County_x', 'ZIP_x': 'ZIP_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'ABS_DIRECT': 'ABS_DIRECT', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'ROAD_NUM_1': 'ROAD_NUM_1', 'ROAD_NAM_1': 'ROAD_NAM_1', 'DIRECTIO_1': 'DIRECTIO_1', 'SEGMENT__1': 'SEGMENT__1', 'SEGMENT__2': 'SEGMENT__2', 'County_y': 'County_y', 'ZIP_y': 'ZIP_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'ABS_DIRE_1': 'ABS_DIRE_1', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'Travel Tim': 'Travel Tim', 'Travel Tim_1': 'Travel Tim_1', 'Travel Tim_2': 'Travel Tim_2', 'Cong Diff': 'Cong Diff', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', });
lyr_CongestionAfternoonZip_6.set('fieldAliases', {'Zip': 'Zip Code', 'PC_NAME': 'PC_NAME', 'PC_TYPE': 'PC_TYPE', 'PA_NAME': 'PA_NAME', 'PA_FIPS': 'PA_FIPS', 'City': 'City', 'County': 'County', 'AREA_SQMI': 'AREA_SQMI', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'ZIP': 'ZIP', 'ZIP_x': 'ZIP_x', 'OBJECTID_x': 'OBJECTID_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'Cong 2012', 'OBJECTID_y': 'OBJECTID_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'Cong 2015', 'cong_diff': 'Cong Diff', 'tT_2012': 'Travel Time 2012', 'tT_2015': 'Travel Time 2015', 'speed_2012': 'Speed 2012', 'speed_2015': 'Speed 2015', 'tT_increas': 'Travel Time Diff', 'congZip201': 'congZip201', 'congZip2_1': 'congZip2_1', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'congDiff': 'congDiff', 'congPercen': 'congPercen', 'tTZip2012': 'tTZip2012', 'tTZip2015': 'tTZip2015', 'travelTPer': 'travelTPer', 'speedZip20': 'speedZip20', 'speedZip_1': 'speedZip_1', 'speedPerce': 'speedPerce', 'Travel Tim': 'Travel Time 2012', 'Travel Tim_1': 'Travel Time 2015', 'Travel Tim_2': 'Travel Time Diff', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', 'Speed Diff': 'Speed Diff', 'Cong Diff': 'Cong Diff', });
lyr_CongestionComparisonStreetPM_7.set('fieldAliases', {'OBJECTID_x': 'OBJECTID_x', 'TMC': 'TMC', 'ROAD_NUMBE': 'ROAD_NUMBE', 'Road': 'Road', 'DIRECTION_': 'DIRECTION_', 'SEGMENT_BE': 'SEGMENT_BE', 'SEGMENT_EN': 'SEGMENT_EN', 'County_x': 'County_x', 'ZIP_x': 'ZIP_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'ABS_DIRECT': 'ABS_DIRECT', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'ROAD_NUM_1': 'ROAD_NUM_1', 'ROAD_NAM_1': 'ROAD_NAM_1', 'DIRECTIO_1': 'DIRECTIO_1', 'SEGMENT__1': 'SEGMENT__1', 'SEGMENT__2': 'SEGMENT__2', 'County_y': 'County_y', 'ZIP_y': 'ZIP_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'ABS_DIRE_1': 'ABS_DIRE_1', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'Travel Tim': 'Travel Tim', 'Travel Tim_1': 'Travel Tim_1', 'Travel Tim_2': 'Travel Tim_2', 'Cong Diff': 'Cong Diff', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', });
lyr_CongestionNoonZip_8.set('fieldAliases', {'Zip': 'Zip', 'PC_NAME': 'PC_NAME', 'PC_TYPE': 'PC_TYPE', 'PA_NAME': 'PA_NAME', 'PA_FIPS': 'PA_FIPS', 'City': 'City', 'County': 'County', 'AREA_SQMI': 'AREA_SQMI', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'ZIP': 'ZIP', 'ZIP_x': 'ZIP_x', 'OBJECTID_x': 'OBJECTID_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'congZip201': 'congZip201', 'congZip2_1': 'congZip2_1', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'congDiff': 'congDiff', 'congPercen': 'congPercen', 'tTZip2012': 'tTZip2012', 'tTZip2015': 'tTZip2015', 'travelTPer': 'travelTPer', 'speedZip20': 'speedZip20', 'speedZip_1': 'speedZip_1', 'speedPerce': 'speedPerce', 'Travel Tim': 'Travel Tim', 'Travel Tim_1': 'Travel Tim_1', 'Travel TIm': 'Travel TIm', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', 'Speed Diff': 'Speed Diff', 'Cong Diff': 'Cong Diff', });
lyr_CongestionComparisonStreetMD_9.set('fieldAliases', {'OBJECTID_x': 'OBJECTID_x', 'TMC': 'TMC', 'ROAD_NUMBE': 'ROAD_NUMBE', 'Road': 'Road', 'DIRECTION_': 'DIRECTION_', 'SEGMENT_BE': 'SEGMENT_BE', 'SEGMENT_EN': 'SEGMENT_EN', 'County_x': 'County_x', 'ZIP_x': 'ZIP_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'ABS_DIRECT': 'ABS_DIRECT', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'ROAD_NUM_1': 'ROAD_NUM_1', 'ROAD_NAM_1': 'ROAD_NAM_1', 'DIRECTIO_1': 'DIRECTIO_1', 'SEGMENT__1': 'SEGMENT__1', 'SEGMENT__2': 'SEGMENT__2', 'County_y': 'County_y', 'ZIP_y': 'ZIP_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'ABS_DIRE_1': 'ABS_DIRE_1', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'Time Trave': 'Time Trave', 'Time Trave_1': 'Time Trave_1', 'Time Trave_2': 'Time Trave_2', 'Cong Diff': 'Cong Diff', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', });
lyr_CongestionMorningZip_10.set('fieldAliases', {'Zip': 'Zip', 'PC_NAME': 'PC_NAME', 'PC_TYPE': 'PC_TYPE', 'PA_NAME': 'PA_NAME', 'PA_FIPS': 'PA_FIPS', 'City': 'City', 'County': 'County', 'AREA_SQMI': 'AREA_SQMI', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'ZIP': 'ZIP', 'ZIP_x': 'ZIP_x', 'OBJECTID_x': 'OBJECTID_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'congZip201': 'congZip201', 'congZip2_1': 'congZip2_1', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'congDiff': 'congDiff', 'congPercen': 'congPercen', 'tTZip2012': 'tTZip2012', 'tTZip2015': 'tTZip2015', 'travelTPer': 'travelTPer', 'speedZip20': 'speedZip20', 'speedZip_1': 'speedZip_1', 'speedPerce': 'speedPerce', 'Travel Tim': 'Travel Tim', 'Travel Tim_1': 'Travel Tim_1', 'Travel Tim_2': 'Travel Tim_2', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', 'Speed Diff': 'Speed Diff', 'Cong Diff': 'Cong Diff', });
lyr_CongestionComparisonStreetAM_11.set('fieldAliases', {'OBJECTID_x': 'OBJECTID_x', 'TMC': 'TMC', 'ROAD_NUMBE': 'ROAD_NUMBE', 'Road': 'Road', 'DIRECTION_': 'DIRECTION_', 'SEGMENT_BE': 'SEGMENT_BE', 'SEGMENT_EN': 'SEGMENT_EN', 'County_x': 'County_x', 'ZIP_x': 'ZIP_x', 'SORT_KEY_x': 'SORT_KEY_x', 'XWAY_x': 'XWAY_x', 'ABS_DIRECT': 'ABS_DIRECT', 'Shape_Leng': 'Shape_Leng', 'cong_2012': 'cong_2012', 'OBJECTID_y': 'OBJECTID_y', 'ROAD_NUM_1': 'ROAD_NUM_1', 'ROAD_NAM_1': 'ROAD_NAM_1', 'DIRECTIO_1': 'DIRECTIO_1', 'SEGMENT__1': 'SEGMENT__1', 'SEGMENT__2': 'SEGMENT__2', 'County_y': 'County_y', 'ZIP_y': 'ZIP_y', 'SORT_KEY_y': 'SORT_KEY_y', 'XWAY_y': 'XWAY_y', 'ABS_DIRE_1': 'ABS_DIRE_1', 'Shape_Le_1': 'Shape_Le_1', 'cong_2015': 'cong_2015', 'cong_diff': 'cong_diff', 'tT_2012': 'tT_2012', 'tT_2015': 'tT_2015', 'speed_2012': 'speed_2012', 'speed_2015': 'speed_2015', 'tT_increas': 'tT_increas', 'Travel Tim': 'Travel Tim', 'Travel Tim_1': 'Travel Tim_1', 'Travel Tim_2': 'Travel Tim_2', 'Cong Diff': 'Cong Diff', 'Cong 2012': 'Cong 2012', 'Cong 2015': 'Cong 2015', 'Speed 2012': 'Speed 2012', 'Speed 2015': 'Speed 2015', });
lyr_ZipCodes_0.set('fieldImages', {'POSTCODE': 'Hidden', 'PC_NAME': 'Hidden', 'PC_TYPE': 'Hidden', 'PA_NAME': 'Hidden', 'PA_FIPS': 'Hidden', 'City': 'Hidden', 'County': 'Hidden', 'AREA_SQMI': 'Hidden', 'SHAPE_AREA': 'Hidden', 'SHAPE_LEN': 'Hidden', });
lyr_Roadsegments_1.set('fieldImages', {'OBJECTID_x': 'Hidden', 'TMC': 'Hidden', 'ROAD_NUMBE': 'Hidden', 'Road': 'Hidden', 'DIRECTION_': 'Hidden', 'SEGMENT_BE': 'Hidden', 'SEGMENT_EN': 'Hidden', 'County_x': 'Hidden', 'ZIP_x': 'Hidden', 'SORT_KEY_x': 'Hidden', 'XWAY_x': 'Hidden', 'ABS_DIRECT': 'Hidden', 'Shape_Leng': 'Hidden', 'travelT_20': 'Hidden', 'OBJECTID_y': 'Hidden', 'ROAD_NUM_1': 'Hidden', 'ROAD_NAM_1': 'Hidden', 'DIRECTIO_1': 'Hidden', 'SEGMENT__1': 'Hidden', 'SEGMENT__2': 'Hidden', 'County_y': 'Hidden', 'ZIP_y': 'Hidden', 'SORT_KEY_y': 'Hidden', 'XWAY_y': 'Hidden', 'ABS_DIRE_1': 'Hidden', 'Shape_Le_1': 'Hidden', 'travelT__1': 'Hidden', 'travelT_in': 'Hidden', });
lyr_CongestionAllZip_2.set('fieldImages', {'Zip': 'TextEdit', 'PC_NAME': 'TextEdit', 'PC_TYPE': 'TextEdit', 'PA_NAME': 'TextEdit', 'PA_FIPS': 'TextEdit', 'City': 'TextEdit', 'County': 'TextEdit', 'AREA_SQMI': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'ZIP': 'TextEdit', 'ZIP_x': 'TextEdit', 'OBJECTID_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'congZip201': 'TextEdit', 'congZip2_1': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'congDiff': 'TextEdit', 'congPercen': 'TextEdit', 'tTZip2012': 'TextEdit', 'tTZip2015': 'TextEdit', 'travelTPer': 'TextEdit', 'speedZip20': 'TextEdit', 'speedZip_1': 'TextEdit', 'speedPerce': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel Tim_2': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', 'S': 'TextEdit', 'Cong Diff': 'TextEdit', });
lyr_CongestionComparisonStreetAll_3.set('fieldImages', {'OBJECTID_x': 'TextEdit', 'TMC': 'TextEdit', 'ROAD_NUMBE': 'TextEdit', 'Road': 'TextEdit', 'DIRECTION_': 'TextEdit', 'SEGMENT_BE': 'TextEdit', 'SEGMENT_EN': 'TextEdit', 'County_x': 'TextEdit', 'ZIP_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'ABS_DIRECT': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'ROAD_NUM_1': 'TextEdit', 'ROAD_NAM_1': 'TextEdit', 'DIRECTIO_1': 'TextEdit', 'SEGMENT__1': 'TextEdit', 'SEGMENT__2': 'TextEdit', 'County_y': 'TextEdit', 'ZIP_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'ABS_DIRE_1': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel Tim_2': 'TextEdit', 'Cong Diff': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', });
lyr_CongestionNightZip_4.set('fieldImages', {'Zip': 'TextEdit', 'PC_NAME': 'TextEdit', 'PC_TYPE': 'TextEdit', 'PA_NAME': 'TextEdit', 'PA_FIPS': 'TextEdit', 'City': 'TextEdit', 'County': 'TextEdit', 'AREA_SQMI': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'ZIP': 'TextEdit', 'ZIP_x': 'TextEdit', 'OBJECTID_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'congZip201': 'TextEdit', 'congZip2_1': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'congDiff': 'TextEdit', 'congPercen': 'TextEdit', 'tTZip2012': 'TextEdit', 'tTZip2015': 'TextEdit', 'travelTPer': 'TextEdit', 'speedZip20': 'TextEdit', 'speedZip_1': 'TextEdit', 'speedPerce': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel Tim_2': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', 'Speed Diff': 'TextEdit', 'Cong Diff': 'TextEdit', });
lyr_CongestionComparisonStreetNT_5.set('fieldImages', {'OBJECTID_x': 'TextEdit', 'TMC': 'TextEdit', 'ROAD_NUMBE': 'TextEdit', 'Road ': 'TextEdit', 'DIRECTION_': 'TextEdit', 'SEGMENT_BE': 'TextEdit', 'SEGMENT_EN': 'TextEdit', 'County_x': 'TextEdit', 'ZIP_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'ABS_DIRECT': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'ROAD_NUM_1': 'TextEdit', 'ROAD_NAM_1': 'TextEdit', 'DIRECTIO_1': 'TextEdit', 'SEGMENT__1': 'TextEdit', 'SEGMENT__2': 'TextEdit', 'County_y': 'TextEdit', 'ZIP_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'ABS_DIRE_1': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel Tim_2': 'TextEdit', 'Cong Diff': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', });
lyr_CongestionAfternoonZip_6.set('fieldImages', {'Zip': 'TextEdit', 'PC_NAME': 'TextEdit', 'PC_TYPE': 'TextEdit', 'PA_NAME': 'TextEdit', 'PA_FIPS': 'TextEdit', 'City': 'TextEdit', 'County': 'TextEdit', 'AREA_SQMI': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'ZIP': 'TextEdit', 'ZIP_x': 'TextEdit', 'OBJECTID_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'congZip201': 'TextEdit', 'congZip2_1': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'congDiff': 'TextEdit', 'congPercen': 'TextEdit', 'tTZip2012': 'TextEdit', 'tTZip2015': 'TextEdit', 'travelTPer': 'TextEdit', 'speedZip20': 'TextEdit', 'speedZip_1': 'TextEdit', 'speedPerce': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel Tim_2': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', 'Speed Diff': 'TextEdit', 'Cong Diff': 'TextEdit', });
lyr_CongestionComparisonStreetPM_7.set('fieldImages', {'OBJECTID_x': 'TextEdit', 'TMC': 'TextEdit', 'ROAD_NUMBE': 'TextEdit', 'Road': 'TextEdit', 'DIRECTION_': 'TextEdit', 'SEGMENT_BE': 'TextEdit', 'SEGMENT_EN': 'TextEdit', 'County_x': 'TextEdit', 'ZIP_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'ABS_DIRECT': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'ROAD_NUM_1': 'TextEdit', 'ROAD_NAM_1': 'TextEdit', 'DIRECTIO_1': 'TextEdit', 'SEGMENT__1': 'TextEdit', 'SEGMENT__2': 'TextEdit', 'County_y': 'TextEdit', 'ZIP_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'ABS_DIRE_1': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel Tim_2': 'TextEdit', 'Cong Diff': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', });
lyr_CongestionNoonZip_8.set('fieldImages', {'Zip': 'TextEdit', 'PC_NAME': 'TextEdit', 'PC_TYPE': 'TextEdit', 'PA_NAME': 'TextEdit', 'PA_FIPS': 'TextEdit', 'City': 'TextEdit', 'County': 'TextEdit', 'AREA_SQMI': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'ZIP': 'TextEdit', 'ZIP_x': 'TextEdit', 'OBJECTID_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'congZip201': 'TextEdit', 'congZip2_1': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'congDiff': 'TextEdit', 'congPercen': 'TextEdit', 'tTZip2012': 'TextEdit', 'tTZip2015': 'TextEdit', 'travelTPer': 'TextEdit', 'speedZip20': 'TextEdit', 'speedZip_1': 'TextEdit', 'speedPerce': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel TIm': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', 'Speed Diff': 'TextEdit', 'Cong Diff': 'TextEdit', });
lyr_CongestionComparisonStreetMD_9.set('fieldImages', {'OBJECTID_x': 'TextEdit', 'TMC': 'TextEdit', 'ROAD_NUMBE': 'TextEdit', 'Road': 'TextEdit', 'DIRECTION_': 'TextEdit', 'SEGMENT_BE': 'TextEdit', 'SEGMENT_EN': 'TextEdit', 'County_x': 'TextEdit', 'ZIP_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'ABS_DIRECT': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'ROAD_NUM_1': 'TextEdit', 'ROAD_NAM_1': 'TextEdit', 'DIRECTIO_1': 'TextEdit', 'SEGMENT__1': 'TextEdit', 'SEGMENT__2': 'TextEdit', 'County_y': 'TextEdit', 'ZIP_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'ABS_DIRE_1': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'Time Trave': 'TextEdit', 'Time Trave_1': 'TextEdit', 'Time Trave_2': 'TextEdit', 'Cong Diff': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', });
lyr_CongestionMorningZip_10.set('fieldImages', {'Zip': 'TextEdit', 'PC_NAME': 'TextEdit', 'PC_TYPE': 'TextEdit', 'PA_NAME': 'TextEdit', 'PA_FIPS': 'TextEdit', 'City': 'TextEdit', 'County': 'TextEdit', 'AREA_SQMI': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'ZIP': 'TextEdit', 'ZIP_x': 'TextEdit', 'OBJECTID_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'congZip201': 'TextEdit', 'congZip2_1': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'congDiff': 'TextEdit', 'congPercen': 'TextEdit', 'tTZip2012': 'TextEdit', 'tTZip2015': 'TextEdit', 'travelTPer': 'TextEdit', 'speedZip20': 'TextEdit', 'speedZip_1': 'TextEdit', 'speedPerce': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel Tim_2': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', 'Speed Diff': 'TextEdit', 'Cong Diff': 'TextEdit', });
lyr_CongestionComparisonStreetAM_11.set('fieldImages', {'OBJECTID_x': 'TextEdit', 'TMC': 'TextEdit', 'ROAD_NUMBE': 'TextEdit', 'Road': 'TextEdit', 'DIRECTION_': 'TextEdit', 'SEGMENT_BE': 'TextEdit', 'SEGMENT_EN': 'TextEdit', 'County_x': 'TextEdit', 'ZIP_x': 'TextEdit', 'SORT_KEY_x': 'TextEdit', 'XWAY_x': 'TextEdit', 'ABS_DIRECT': 'TextEdit', 'Shape_Leng': 'TextEdit', 'cong_2012': 'TextEdit', 'OBJECTID_y': 'TextEdit', 'ROAD_NUM_1': 'TextEdit', 'ROAD_NAM_1': 'TextEdit', 'DIRECTIO_1': 'TextEdit', 'SEGMENT__1': 'TextEdit', 'SEGMENT__2': 'TextEdit', 'County_y': 'TextEdit', 'ZIP_y': 'TextEdit', 'SORT_KEY_y': 'TextEdit', 'XWAY_y': 'TextEdit', 'ABS_DIRE_1': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'cong_2015': 'TextEdit', 'cong_diff': 'TextEdit', 'tT_2012': 'TextEdit', 'tT_2015': 'TextEdit', 'speed_2012': 'TextEdit', 'speed_2015': 'TextEdit', 'tT_increas': 'TextEdit', 'Travel Tim': 'TextEdit', 'Travel Tim_1': 'TextEdit', 'Travel Tim_2': 'TextEdit', 'Cong Diff': 'TextEdit', 'Cong 2012': 'TextEdit', 'Cong 2015': 'TextEdit', 'Speed 2012': 'TextEdit', 'Speed 2015': 'TextEdit', });
lyr_ZipCodes_0.set('fieldLabels', {'POSTCODE': 'inli ', 'PC_NAME': 'no label', 'PC_TYPE': 'no label', 'PA_NAME': 'no label', 'PA_FIPS': 'no label', 'City': 'no label', 'County': 'no label', 'AREA_SQMI': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', });
lyr_Roadsegments_1.set('fieldLabels', {});
lyr_CongestionAllZip_2.set('fieldLabels', {'Zip': 'inline label', 'City': 'inline label', 'County': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel Tim_2': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', 'Cong Diff': 'inline label', });
lyr_CongestionComparisonStreetAll_3.set('fieldLabels', {'Road': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel Tim_2': 'inline label', 'Cong Diff': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', });
lyr_CongestionNightZip_4.set('fieldLabels', {'Zip': 'inline label', 'City': 'inline label', 'County': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel Tim_2': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', 'Cong Diff': 'inline label', });
lyr_CongestionComparisonStreetNT_5.set('fieldLabels', {'Road ': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel Tim_2': 'inline label', 'Cong Diff': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', });
lyr_CongestionAfternoonZip_6.set('fieldLabels', {'Zip': 'inline label', 'City': 'inline label', 'County': 'inline label', 'cong_2012': 'inline label', 'cong_2015': 'inline label', 'cong_diff': 'inline label', 'tT_2012': 'inline label', 'tT_2015': 'inline label', 'speed_2012': 'inline label', 'speed_2015': 'inline label', 'tT_increas': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel Tim_2': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', 'Cong Diff': 'inline label', });
lyr_CongestionComparisonStreetPM_7.set('fieldLabels', {'Road': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel Tim_2': 'inline label', 'Cong Diff': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', });
lyr_CongestionNoonZip_8.set('fieldLabels', {'Zip': 'inline label', 'City': 'inline label', 'County': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel TIm': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', 'Speed Diff': 'inline label', 'Cong Diff': 'inline label', });
lyr_CongestionComparisonStreetMD_9.set('fieldLabels', {'Road': 'inline label', 'Time Trave': 'inline label', 'Time Trave_1': 'inline label', 'Time Trave_2': 'inline label', 'Cong Diff': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', });
lyr_CongestionMorningZip_10.set('fieldLabels', {'Zip': 'inline label', 'City': 'inline label', 'County': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel Tim_2': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', 'Speed Diff': 'inline label', 'Cong Diff': 'inline label', });
lyr_CongestionComparisonStreetAM_11.set('fieldLabels', {'TMC': 'inline label', 'ROAD_NUMBE': 'inline label', 'Road': 'inline label', 'DIRECTION_': 'inline label', 'SEGMENT_BE': 'inline label', 'SEGMENT_EN': 'inline label', 'County_x': 'inline label', 'ZIP_x': 'inline label', 'SORT_KEY_x': 'inline label', 'XWAY_x': 'inline label', 'ABS_DIRECT': 'inline label', 'Shape_Leng': 'inline label', 'cong_2012': 'inline label', 'OBJECTID_y': 'inline label', 'ROAD_NUM_1': 'inline label', 'ROAD_NAM_1': 'inline label', 'DIRECTIO_1': 'inline label', 'SEGMENT__1': 'inline label', 'SEGMENT__2': 'inline label', 'County_y': 'inline label', 'ZIP_y': 'inline label', 'SORT_KEY_y': 'inline label', 'XWAY_y': 'inline label', 'ABS_DIRE_1': 'inline label', 'Shape_Le_1': 'inline label', 'cong_2015': 'inline label', 'cong_diff': 'inline label', 'tT_2012': 'inline label', 'tT_2015': 'inline label', 'speed_2012': 'inline label', 'speed_2015': 'inline label', 'tT_increas': 'inline label', 'Travel Tim': 'inline label', 'Travel Tim_1': 'inline label', 'Travel Tim_2': 'inline label', 'Cong Diff': 'inline label', 'Cong 2012': 'inline label', 'Cong 2015': 'inline label', 'Speed 2012': 'inline label', 'Speed 2015': 'inline label', });
lyr_CongestionComparisonStreetAM_11.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});